profiles/urls.py
from django.conf.urls import patterns, include, url
from profiles.views import UserProfileDetailView, UserProfileEditView

from django.contrib.auth.decorators import login_required as auth

urlpatterns = patterns('',
	url(r'^edit_profile/$', auth(UserProfileEditView.as_view()), name='edit_profile'),
    url(r'^(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name='profile'),    
)

steelrumors/urls.py
from django.conf.urls import patterns, include, url

from links.views import LinkListView, LinkCreateView, LinkDetailView, LinkDeleteView, LinkUpdateView
from links.views import VoteFormView

from django.contrib import admin
from django.contrib.auth.decorators import login_required as auth

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', LinkListView.as_view(), name='home'),
    url(r'^link/create/$', auth(LinkCreateView.as_view()), name='link_create'),
    url(r'^link/update/(?P<pk>\d+)/$', auth(LinkUpdateView.as_view()), name='link_update'),
    url(r'^link/delete/(?P<pk>\d+)/$', auth(LinkDeleteView.as_view()), name='link_delete'),
    url(r'^link/(?P<pk>\d+)/$', LinkDetailView.as_view(), name='link_detail'),
    url(r'^vote/$', auth(VoteFormView.as_view()), name='vote'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^users/', include('profiles.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
)

links/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count

from django.core.urlresolvers import reverse
from django.utils.timezone import now

class LinkVoteCountManager(models.Manager):
	def get_query_set(self):
		return super(LinkVoteCountManager, self).get_query_set().annotate(
			votes=Count('vote')).order_by('rank_score', '-votes')

class Link(models.Model):
	title = models.CharField("Headline", max_length=250)
	submitter = models.ForeignKey(User)
	submitted_on = models.DateTimeField(auto_now_add=True)
	rank_score = models.FloatField(default=0.0)
	url = models.URLField("URL", max_length=250, blank=True)
	description = models.TextField(blank=True)
	with_votes = LinkVoteCountManager()
	objects = models.Manager() #default manager

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("link_detail", kwargs={"pk": str(self.id)})

	def set_rank(self):
		SECS_IN_HOUR = float(60*60)
		GRAVITY = 1.2

		delta = now() - self.submitted_on
		item_hour_age = delta.total_seconds()
		votes = self.votes - 1
		self.rank_score = votes / pow((item_hour_age+1), GRAVITY)
		self.save()

class Vote(models.Model):
	voter = models.ForeignKey(User)
	link = models.ForeignKey(Link)

	def __unicode(self):
		return "%s upvoted %s" % (self.voter.username, self.link.title)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
	user = models.OneToOneField(User, unique=True)
	bio = models.TextField(null=True)

	def __unicode__(self):
		return "%s's profile" % self.user


def create_profile(sender, instance, created, **kwargs):
	if created:
		profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

links/forms.py
from .models import Link, Vote
from django import forms

class LinkForm(forms.ModelForm):
	class Meta:
		model = Link
		exclude = ("submitter", "rank_score",)


class VoteForm(forms.ModelForm):
	class Meta:
		model = Vote

profiles/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ('user',)

links/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import Link, Vote
from .forms import LinkForm, VoteForm

from django.core.urlresolvers import reverse_lazy
from django.contrib.comments.models import Comment

from django.shortcuts import redirect, get_object_or_404

import json
from django.http import HttpResponse

class RandomGossipMxin(object):
	def get_context_data(self, **kwargs):
		context = super(RandomGossipMxin, self).get_context_data(**kwargs)
		context[u"randomquip"] = Comment.objects.order_by('?')[0]
		return context

class LinkListView(RandomGossipMxin, ListView):
	model = Link

	queryset = Link.with_votes.all()
	paginate_by = 3

	def get_context_data(self, **kwargs):
		context = super(LinkListView, self).get_context_data(**kwargs)
		if self.request.user.is_authenticated():
			voted = Vote.objects.filter(voter=self.request.user)
			links_in_page = [link.id for link in context["object_list"]]
			voted = voted.filter(link_id__in=links_in_page)
			voted = voted.values_list('link_id', flat=True)
			context["voted"] = voted
		return context


class LinkCreateView(CreateView):
	model = Link
	form_class = LinkForm

	def form_valid(self, form):
		f = form.save(commit=False)
		f.rank_score = 0.0
		f.submitter = self.request.user
		f.save()

		return super(CreateView, self).form_valid(form)

class LinkDetailView(DetailView):
	model = Link


class LinkUpdateView(UpdateView):
	model = Link
	form_class = LinkForm

class LinkDeleteView(DeleteView):
	model = Link
	success_url = reverse_lazy("home")

class JSONFormMixin(object):
	def create_response(self, vdict=dict(), valid_form=True):
		response = HttpResponse(json.dumps(vdict), content_type='application/json')
		response.status = 200 if valid_form else 500
		return response

class VoteFormBaseView(FormView):
	form_class = VoteForm

	def create_response(self, vdict=dict(), valid_form=True):
		response = HttpResponse(json.dumps(vdict))
		response.status = 200 if valid_form else 500
		return response

	def form_valid(self, form):
		link = get_object_or_404(Link, pk=form.data["link"])
		user = self.request.user
		prev_votes = Vote.objects.filter(voter=user, link=link)
		has_voted = (prev_votes.count() > 0)

		ret = {"success": 1}
		if not has_voted:
			v = Vote.objects.create(voter=user, link=link)
			ret["voteobj"] = v.id
			print "Voted"
		else:
			prev_votes[0].delete()
			print "Removed Vote"

		return self.create_response(ret, False)

	def form_invalid(self, form):
		ret = {"sucess": 0, "form_errors": form.errors}
		return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

profiles/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth import get_user_model

from .models import UserProfile
from .forms import UserProfileForm

from django.core.urlresolvers import reverse

class UserProfileDetailView(DetailView):
	model = get_user_model()
	slug_field = "username"
	template_name = "user_detail.html"

	def get_object(self, queryset=None):
		user = super(UserProfileDetailView, self).get_object(queryset)
		UserProfile.objects.get_or_create(user=user)
		return user

class UserProfileEditView(UpdateView):
	model = UserProfile
	form_class = UserProfileForm
	template_name = "edit_profile.html"

	def get_object(self, queryset=None):
		return UserProfile.objects.get_or_create(user=self.request.user)[0]

	def get_success_url(self):
		return reverse("profile", kwargs={'slug': self.request.user})

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name ="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Bootstrap  -->

		
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!-- 
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
		-->

		<link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
		<!-- <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-glyphicons.css' %}" rel="stylesheet"> -->

		<title>{% block title %}Steel Rumors{% endblock %}</title>
	</head>

	<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Steel Rumors</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Search</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	      	{% if request.user.is_authenticated %}
	      	<li><a href="{% url 'link_create' %}">Create Link</a></li>
	        	<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="{% url 'profile' slug=user.username %}">Profile</a></li>
		            <li><a href="{% url 'account_logout' %}">Logout</a></li>
		          </ul>
		        </li>
	        {% else %}    
	        	<li><a href="{% url 'account_login' %}">Login</a></li>
	        {% endif %}
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
    </div>

		<div class="container-fluid">
    		<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					{% block content %}

					{% endblock %}
				</div>
			</div>
		</div>

		<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>	
		<script src="{% static 'js/hackernews-ajax.js' %}"></script>

	</body>
</html>

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>

{% endblock %}

templates/links/link_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a> 
  <p><input type="submit" value="Confirm deletion" /></p>
</form> 

{% endblock %}

templates/links/link_detail.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}

<div class="desc">
  {{ object.description }}
</div>

<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'link_detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>


{% endblock %}

templates/links/link_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add">
</form>
{% endblock %}

templates/links/link_list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
{% if is_paginated %}
<ol start="{{ page_obj.start_index }}">
{% else %}
<ol>
{% endif %}
{% for link in object_list %}
<form method="post" action="{% url 'vote' %}" class="vote_form">
  <li>[<span class="link_votes_count">{{ link.votes }}</span>]
    {% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    {% if not user.is_authenticated %}
    <button disabled title="Please login to vote">+</button>
    {% elif link.pk not in voted %}
    <button>+</button>
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{% url 'link_detail' pk=link.pk %}">
      <b>{{ link.title }}</b>
      {% get_comment_count for link as comment_count %}
      {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
  </li>
</form>
{% endfor %}
</ol>

{% if is_paginated %}
	<ul class="pager">
		{% if page_obj.has_previous %}
	  <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
	  {% endif %}

	  {% if page_obj.has_next %}
	  <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
	  {% endif %}
	</ul>
{% endif %}

<blockquote style="background-color: #ddd; padding: 4px; border-radius: 10px; margin: 10px 0; color: #666; font-size: smaller; text-shadow: rgba(255,255,255,0.8) 1px 1px 0;">
{{ randomquip.comment|truncatechars:140 }}
</blockquote>

{% endblock %}

templates/user_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.username }}'s Profile</h2>
{% if object.userprofile.bio %}
<div>
<b>Bio:</b>
{{ object.userprofile.bio }}
</div>
{% endif %}
{% if object.username == user.username %}
<p><a href='{% url "edit_profile" %}'>Edit my profile</a></p>
{% endif %}

{% if "zodcat" in object.userprofile.bio %}
<style>
html {
  background: #EEE url("/static/img/zod.jpg");
}
</style>
{% endif %}

{% endblock %}